-- Create the test123 schema
CREATE SCHEMA IF NOT EXISTS test123;

-- Grant privileges to testuser
GRANT ALL PRIVILEGES ON SCHEMA test123 TO testuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA test123 TO testuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA test123 TO testuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA test123 GRANT ALL ON TABLES TO testuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA test123 GRANT ALL ON SEQUENCES TO testuser;
